bus:
  path: localhost:10001
command: svc/eva-data-validator
react_to_fail: true
timeout:
  startup: 30.0
user: nobody
workers: 1
config:
  locale: ru
  validations:
    product_create:
      mp: "required|string"
      code_rc: "required|integer|unique:db.dictionary.product,code_rc"
      name: "required|string"
      multiplicity: "nullable|integer|min:1"
      barcode: "required|string|unique:db.dictionary.product,barcode"
      subject: "required|string"
      packaging_type: "nullable|string"
    product_update:
      id: "required|integer"
      mp: "sometimes|string"
      code_rc: "sometimes|integer|unique:db.dictionary.product,code_rc,id"
      name: "sometimes|string"
      multiplicity: "sometimes|integer|min:1"
      barcode: "sometimes|string|unique:db.dictionary.product,barcode,id"
      subject: "sometimes|string"
      packaging_type: "sometimes|string"
    product_delete:
      id: "required|integer"
    product_get:
      mp: "sometimes|string"
      code_rc: "sometimes|integer|unique:db.dictionary.product,code_rc,id"
      name: "sometimes|string"
      multiplicity: "sometimes|integer|min:1"
      barcode: "sometimes|string|unique:db.dictionary.product,barcode,id"
      subject: "sometimes|string"
      packaging_type: "sometimes|string"
